### ISSUE TITLE
Fetch Error

### ISSUE THREAD

**Issue by notadevps** [vierofernando/uselessapi.js#1]
Unhandled promise rejection: FetchError: request to https://useless-api.vierofernando.repl.co/texttoimage?text=ggh failed, reason: write EPROTO 7532:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1544:SSL alert number 80     

    at ClientRequest.<anonymous> (C:\Users\sahil\Desktop\voltv2\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  type: 'system',
  errno: 'EPROTO',
  code: 'EPROTO'
}

Got This In My Console

Is Api Down ?

**Comment by vierofernando** [comment]
The issue should be fix around now, the API is up again, sorry for the inconvenience!
